apiVersion: apps/v1
kind: Deployment
metadata:
  name: examination-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: examination
  template:
    metadata:
      labels:
        app: examination
    spec:
      containers:
      - name: examination-service
        image: junaid757/examination-service:latest
        ports:
        - containerPort: 3004
---
apiVersion: v1
kind: Service
metadata:
  name: examination-service
spec:
  selector:
    app: examination
  ports:
    - protocol: TCP
      port: 3004
      targetPort: 3004
  type: LoadBalancer
