apiVersion: apps/v1
kind: Deployment
metadata:
  name: faculty-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: faculty
  template:
    metadata:
      labels:
        app: faculty
    spec:
      containers:
      - name: faculty-service
        image: junaid757/faculty-service:latest
        ports:
        - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: faculty-service
spec:
  selector:
    app: faculty
  ports:
    - protocol: TCP
      port: 3002
      targetPort: 3002
  type: LoadBalancer
