apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendance-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attendance
  template:
    metadata:
      labels:
        app: attendance
    spec:
      containers:
      - name: attendance-service
        image: junaid757/attendance-service:latest

        ports:
        - containerPort: 3003
---
apiVersion: v1
kind: Service
metadata:
  name: attendance-service
spec:
  selector:
    app: attendance
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: LoadBalancer
